import "dotenv/config";
import { PrismaClient } from "../generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const brands = [
  { name: "Samsung", slug: "samsung" },
  { name: "Apple", slug: "apple" },
  { name: "Xiaomi", slug: "xiaomi" },
  { name: "OPPO", slug: "oppo" },
  { name: "Realme", slug: "realme" },
  { name: "ASUS", slug: "asus" },
  { name: "Lenovo", slug: "lenovo" },
  { name: "Acer", slug: "acer" },
  { name: "HP Inc.", slug: "hp-inc" },
  { name: "vivo", slug: "vivo" },
];

const gadgets = [
  // ── Smartphone / HP ─────────────────────────────────────────────────────
  {
    name: "Samsung Galaxy S24 FE",
    slug: "samsung-galaxy-s24-fe",
    category: "HP" as const,
    brandSlug: "samsung",
    priceIdr: 7_999_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=Galaxy+S24+FE",
    shortDesc: "Flagship experience dengan Exynos 2500, layar Dynamic AMOLED 6.7\"",
    specs: {
      chipset: "Exynos 2500",
      cpu: "Octa-core (1x3.3 GHz + 3x2.75 GHz + 4x2.0 GHz)",
      gpu: "Xclipse 950",
      ram: "8 GB",
      storage: "256 GB",
      expandableStorage: false,
      display: {
        size: "6.7 inci",
        resolution: "1080 x 2340",
        type: "Dynamic AMOLED 2X",
        refreshRate: "120Hz",
      },
      rearCamera: "50 MP (f/1.8) + 10 MP (f/2.4) + 12 MP (f/2.2)",
      frontCamera: "10 MP (f/2.4)",
      battery: { capacity: "4700 mAh", charging: "25W Fast Charging" },
      os: "Android 15 (One UI 7)",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.3, NFC",
      weight: "213 gram",
      waterResistance: "IP68",
      fingerprint: "Under-display optical",
    },
    sourceUrl: "https://www.samsung.com/id/smartphones/galaxy-s/",
  },
  {
    name: "Xiaomi 14T",
    slug: "xiaomi-14t",
    category: "HP" as const,
    brandSlug: "xiaomi",
    priceIdr: 6_499_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=Xiaomi+14T",
    shortDesc: "Dimensity 8300-Ultra, Leica optics, AMOLED 144Hz harga terjangkau",
    specs: {
      chipset: "MediaTek Dimensity 8300-Ultra",
      cpu: "Octa-core (4x3.35 GHz Cortex-A715 + 4x2.20 GHz Cortex-A510)",
      gpu: "Mali-G615 MC6",
      ram: "12 GB",
      storage: "256 GB",
      expandableStorage: false,
      display: {
        size: "6.67 inci",
        resolution: "1220 x 2712",
        type: "AMOLED",
        refreshRate: "144Hz",
      },
      rearCamera: "50 MP (f/1.7, Leica) + 50 MP Telephoto + 12 MP Ultrawide",
      frontCamera: "32 MP",
      battery: { capacity: "5000 mAh", charging: "67W Turbo Charging" },
      os: "Android 14 (HyperOS 2)",
      connectivity: "5G, Wi-Fi 6E, Bluetooth 5.4, NFC",
      weight: "193 gram",
      waterResistance: "IP68",
      fingerprint: "Under-display optical",
    },
    sourceUrl: "https://www.mi.com/id/product/xiaomi-14t",
  },
  {
    name: "OPPO Reno12 F 5G",
    slug: "oppo-reno12-f-5g",
    category: "HP" as const,
    brandSlug: "oppo",
    priceIdr: 3_999_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=Reno12+F",
    shortDesc: "Mid-range stylish dengan Dimensity 6300, kamera 50 MP Portrait",
    specs: {
      chipset: "MediaTek Dimensity 6300",
      ram: "8 GB",
      storage: "256 GB",
      expandableStorage: true,
      display: {
        size: "6.67 inci",
        resolution: "1080 x 2400",
        type: "AMOLED",
        refreshRate: "120Hz",
      },
      rearCamera: "50 MP (f/1.8) + 2 MP depth",
      frontCamera: "32 MP",
      battery: { capacity: "5000 mAh", charging: "45W SUPERVOOC" },
      os: "Android 14 (ColorOS 14.1)",
      connectivity: "5G, Wi-Fi 5, Bluetooth 5.3",
      weight: "186 gram",
      waterResistance: "IP54",
      fingerprint: "Side-mounted",
    },
    sourceUrl: "https://www.oppo.com/id/smartphones/series-reno/reno12-f-5g/",
  },
  {
    name: "Realme 13 Pro+ 5G",
    slug: "realme-13-pro-plus-5g",
    category: "HP" as const,
    brandSlug: "realme",
    priceIdr: 5_499_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=Realme+13+Pro%2B",
    shortDesc: "Snapdragon 7s Gen 3, Sony LYT-600 sensor, 120Hz AMOLED",
    specs: {
      chipset: "Snapdragon 7s Gen 3",
      ram: "12 GB",
      storage: "512 GB",
      expandableStorage: false,
      display: {
        size: "6.7 inci",
        resolution: "1080 x 2412",
        type: "AMOLED",
        refreshRate: "120Hz",
      },
      rearCamera: "50 MP Sony LYT-600 (f/1.8) + 50 MP Telephoto + 8 MP Ultrawide",
      frontCamera: "32 MP",
      battery: { capacity: "5200 mAh", charging: "80W SUPERVOOC" },
      os: "Android 14 (realme UI 5)",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.4, NFC",
      weight: "190 gram",
      fingerprint: "Under-display optical",
    },
    sourceUrl: "https://www.realme.com/id/realme-13-pro-plus",
  },
  {
    name: "vivo V40 5G",
    slug: "vivo-v40-5g",
    category: "HP" as const,
    brandSlug: "vivo",
    priceIdr: 5_699_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=vivo+V40",
    shortDesc: "Snapdragon 7 Gen 3, ZEISS optics, 6.78\" AMOLED 120Hz ultra-slim",
    specs: {
      chipset: "Snapdragon 7 Gen 3",
      ram: "12 GB",
      storage: "256 GB",
      expandableStorage: false,
      display: {
        size: "6.78 inci",
        resolution: "1260 x 2800",
        type: "AMOLED",
        refreshRate: "120Hz",
      },
      rearCamera: "50 MP ZEISS (f/1.88) + 50 MP Ultrawide",
      frontCamera: "50 MP",
      battery: { capacity: "5500 mAh", charging: "80W FlashCharge" },
      os: "Android 14 (Funtouch OS 14)",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.4, NFC",
      weight: "192 gram",
      waterResistance: "IP68",
      fingerprint: "Under-display optical",
    },
    sourceUrl: "https://www.vivo.com/id/products/v40",
  },
  {
    name: "Samsung Galaxy A55 5G",
    slug: "samsung-galaxy-a55-5g",
    category: "HP" as const,
    brandSlug: "samsung",
    priceIdr: 5_199_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=Galaxy+A55",
    shortDesc: "Exynos 1480, Super AMOLED 120Hz, IP67, 4 tahun update OS",
    specs: {
      chipset: "Exynos 1480",
      ram: "8 GB",
      storage: "256 GB",
      expandableStorage: true,
      display: {
        size: "6.6 inci",
        resolution: "1080 x 2340",
        type: "Super AMOLED",
        refreshRate: "120Hz",
      },
      rearCamera: "50 MP OIS (f/1.8) + 12 MP Ultrawide + 5 MP Macro",
      frontCamera: "32 MP",
      battery: { capacity: "5000 mAh", charging: "25W Fast Charging" },
      os: "Android 14 (One UI 6.1)",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.3, NFC",
      weight: "213 gram",
      waterResistance: "IP67",
      fingerprint: "Under-display optical",
    },
    sourceUrl: "https://www.samsung.com/id/smartphones/galaxy-a/",
  },
  {
    name: "Xiaomi Redmi Note 13 Pro 5G",
    slug: "xiaomi-redmi-note-13-pro-5g",
    category: "HP" as const,
    brandSlug: "xiaomi",
    priceIdr: 3_699_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=Redmi+Note+13+Pro",
    shortDesc: "Dimensity 7200-Ultra, 200 MP OIS, AMOLED 120Hz 1.5K",
    specs: {
      chipset: "MediaTek Dimensity 7200-Ultra",
      ram: "8 GB",
      storage: "256 GB",
      expandableStorage: false,
      display: {
        size: "6.67 inci",
        resolution: "1220 x 2712",
        type: "AMOLED",
        refreshRate: "120Hz",
      },
      rearCamera: "200 MP OIS (f/1.65) + 8 MP Ultrawide + 2 MP Macro",
      frontCamera: "16 MP",
      battery: { capacity: "5100 mAh", charging: "67W Turbo Charging" },
      os: "Android 13 (MIUI 14)",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.3, NFC",
      weight: "187 gram",
      waterResistance: "IP54",
      fingerprint: "Side-mounted",
    },
    sourceUrl: "https://www.mi.com/id/product/redmi-note-13-pro-5g",
  },
  {
    name: "OPPO A3 Pro 5G",
    slug: "oppo-a3-pro-5g",
    category: "HP" as const,
    brandSlug: "oppo",
    priceIdr: 2_799_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=OPPO+A3+Pro",
    shortDesc: "Dimensity 6300, 6.7\" AMOLED 120Hz, baterai 5000 mAh harga entry",
    specs: {
      chipset: "MediaTek Dimensity 6300",
      ram: "8 GB",
      storage: "128 GB",
      expandableStorage: true,
      display: {
        size: "6.7 inci",
        resolution: "1080 x 2412",
        type: "AMOLED",
        refreshRate: "120Hz",
      },
      rearCamera: "50 MP (f/1.8)",
      frontCamera: "8 MP",
      battery: { capacity: "5000 mAh", charging: "45W SUPERVOOC" },
      os: "Android 14 (ColorOS 14)",
      connectivity: "5G, Wi-Fi 5, Bluetooth 5.3",
      weight: "187 gram",
      waterResistance: "IP69",
      fingerprint: "Side-mounted",
    },
    sourceUrl: "https://www.oppo.com/id/smartphones/series-a/a3-pro-5g/",
  },
  {
    name: "Apple iPhone 15",
    slug: "apple-iphone-15",
    category: "HP" as const,
    brandSlug: "apple",
    priceIdr: 11_999_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=iPhone+15",
    shortDesc: "A16 Bionic, Dynamic Island, kamera 48 MP, USB-C pertama untuk iPhone",
    specs: {
      chipset: "Apple A16 Bionic",
      cpu: "Hexa-core (2x3.46 GHz Everest + 4x2.02 GHz Sawtooth)",
      gpu: "Apple GPU 5-core",
      ram: "6 GB",
      storage: "128 GB",
      expandableStorage: false,
      display: {
        size: "6.1 inci",
        resolution: "1170 x 2532",
        type: "Super Retina XDR OLED",
        refreshRate: "60Hz",
      },
      rearCamera: "48 MP Main (f/1.6) + 12 MP Ultrawide",
      frontCamera: "12 MP TrueDepth",
      battery: { capacity: "3349 mAh", charging: "20W Fast Charging" },
      os: "iOS 17",
      connectivity: "5G, Wi-Fi 6, Bluetooth 5.3, NFC, Ultra Wideband",
      weight: "171 gram",
      waterResistance: "IP68",
      fingerprint: "Face ID",
    },
    sourceUrl: "https://www.apple.com/id/iphone-15/",
  },
  {
    name: "Realme C65 5G",
    slug: "realme-c65-5g",
    category: "HP" as const,
    brandSlug: "realme",
    priceIdr: 1_899_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=Realme+C65",
    shortDesc: "Entry-level 5G terjangkau, Dimensity 6100+, baterai 5000 mAh",
    specs: {
      chipset: "MediaTek Dimensity 6100+",
      ram: "6 GB",
      storage: "128 GB",
      expandableStorage: true,
      display: {
        size: "6.67 inci",
        resolution: "720 x 1604",
        type: "IPS LCD",
        refreshRate: "90Hz",
      },
      rearCamera: "50 MP (f/1.8) + AI",
      frontCamera: "8 MP",
      battery: { capacity: "5000 mAh", charging: "45W SUPERVOOC" },
      os: "Android 14 (realme UI 5 Go)",
      connectivity: "5G, Wi-Fi 5, Bluetooth 5.3",
      weight: "189 gram",
      fingerprint: "Side-mounted",
    },
    sourceUrl: "https://www.realme.com/id/realme-c65-5g",
  },

  // ── Laptop ─────────────────────────────────────────────────────────────
  {
    name: "ASUS Vivobook 16X OLED",
    slug: "asus-vivobook-16x-oled",
    category: "LAPTOP" as const,
    brandSlug: "asus",
    priceIdr: 10_999_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=Vivobook+16X",
    shortDesc: "Layar OLED 16\" 120Hz, Ryzen 7 7730U, RAM 16 GB, cocok kreator",
    specs: {
      cpu: "AMD Ryzen 7 7730U (8 core, 4.5 GHz boost)",
      gpu: "AMD Radeon Graphics (integrated)",
      ram: "16 GB DDR4 3200MHz",
      storage: "512 GB PCIe NVMe SSD",
      display: {
        size: "16 inci",
        resolution: "1920 x 1200",
        type: "OLED",
        refreshRate: "120Hz",
      },
      battery: { capacity: "70 Wh", charging: "96W fast charge" },
      os: "Windows 11 Home",
      ports: "1x USB-A 3.2, 2x USB-A 3.1, 1x USB-C 3.2, 1x HDMI 1.4, SD card",
      keyboard: "Backlit chiclet keyboard",
      connectivity: "Wi-Fi 6, Bluetooth 5.3",
      weight: "1.88 kg",
    },
    sourceUrl: "https://www.asus.com/id/laptops/for-home/vivobook/",
  },
  {
    name: "Lenovo IdeaPad Slim 5 Gen 9",
    slug: "lenovo-ideapad-slim-5-gen-9",
    category: "LAPTOP" as const,
    brandSlug: "lenovo",
    priceIdr: 9_499_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=IdeaPad+Slim+5",
    shortDesc: "Intel Core Ultra 5 125U, layar IPS 14\" 300 nits, tipis & ringan",
    specs: {
      cpu: "Intel Core Ultra 5 125U (12 core, 4.3 GHz boost)",
      gpu: "Intel Arc Graphics (integrated)",
      ram: "16 GB LPDDR5x",
      storage: "512 GB NVMe SSD",
      display: {
        size: "14 inci",
        resolution: "1920 x 1200",
        type: "IPS Anti-glare",
        refreshRate: "60Hz",
      },
      battery: { capacity: "60 Wh", charging: "65W USB-C" },
      os: "Windows 11 Home",
      ports: "2x USB-A 3.1, 2x USB-C (USB4), HDMI 2.1, 3.5mm audio",
      keyboard: "Backlit, full-size",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      weight: "1.46 kg",
    },
    sourceUrl: "https://www.lenovo.com/id/id/laptops/ideapad/ideapad-slim-series/",
  },
  {
    name: "Acer Aspire 5 A515",
    slug: "acer-aspire-5-a515",
    category: "LAPTOP" as const,
    brandSlug: "acer",
    priceIdr: 7_499_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=Aspire+5",
    shortDesc: "Ryzen 5 7530U, layar 15.6\" FHD IPS, budget all-rounder terbaik",
    specs: {
      cpu: "AMD Ryzen 5 7530U (6 core, 4.5 GHz boost)",
      gpu: "AMD Radeon Graphics (integrated)",
      ram: "8 GB DDR4",
      storage: "512 GB PCIe SSD",
      display: {
        size: "15.6 inci",
        resolution: "1920 x 1080",
        type: "IPS",
        refreshRate: "60Hz",
      },
      battery: { capacity: "50 Wh", charging: "45W" },
      os: "Windows 11 Home",
      ports: "1x USB-A 3.2, 2x USB-A 2.0, 1x USB-C, 1x HDMI, SD card, Ethernet",
      keyboard: "Full-size with numpad",
      connectivity: "Wi-Fi 6, Bluetooth 5.1",
      weight: "1.8 kg",
    },
    sourceUrl: "https://www.acer.com/id-id/laptops/aspire/aspire-5",
  },
  {
    name: "HP Pavilion 15 eg3",
    slug: "hp-pavilion-15-eg3",
    category: "LAPTOP" as const,
    brandSlug: "hp-inc",
    priceIdr: 9_999_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=HP+Pavilion+15",
    shortDesc: "Intel Core i5-1335U, OLED FHD 60Hz, desain premium dengan harga mid",
    specs: {
      cpu: "Intel Core i5-1335U (10 core, 4.6 GHz boost)",
      gpu: "Intel Iris Xe Graphics",
      ram: "16 GB DDR4 3200MHz",
      storage: "512 GB NVMe SSD",
      display: {
        size: "15.6 inci",
        resolution: "1920 x 1080",
        type: "OLED",
        refreshRate: "60Hz",
      },
      battery: { capacity: "70 Wh", charging: "65W USB-C" },
      os: "Windows 11 Home",
      ports: "1x USB-A 3.1, 2x USB-A, 1x USB-C, 1x HDMI 2.1, SD card",
      keyboard: "Backlit full-size",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      weight: "1.75 kg",
    },
    sourceUrl: "https://www.hp.com/id-id/shop/pdp/hp-pavilion-laptop-15",
  },
  {
    name: "ASUS ROG Zephyrus G14 2024",
    slug: "asus-rog-zephyrus-g14-2024",
    category: "LAPTOP" as const,
    brandSlug: "asus",
    priceIdr: 25_999_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=ROG+Zephyrus+G14",
    shortDesc: "Gaming flagship: Ryzen AI 9 HX 370 + RTX 4070, OLED 165Hz AniMe Matrix",
    specs: {
      cpu: "AMD Ryzen AI 9 HX 370 (12 core, 5.1 GHz boost)",
      gpu: "NVIDIA GeForce RTX 4070 8GB GDDR6",
      ram: "32 GB LPDDR5x 7500MHz",
      storage: "1 TB PCIe 4.0 NVMe SSD",
      display: {
        size: "14 inci",
        resolution: "2560 x 1600",
        type: "OLED",
        refreshRate: "165Hz",
      },
      battery: { capacity: "73 Wh", charging: "100W USB-C" },
      os: "Windows 11 Home",
      ports: "1x USB-A 3.2, 2x USB-C (USB4), 1x HDMI 2.1, 1x SD card, 3.5mm",
      keyboard: "Backlit RGB, per-key",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      weight: "1.65 kg",
    },
    sourceUrl: "https://rog.asus.com/id/laptops/rog-zephyrus/rog-zephyrus-g14-2024/",
  },
  {
    name: "Lenovo LOQ 15IRX9",
    slug: "lenovo-loq-15irx9",
    category: "LAPTOP" as const,
    brandSlug: "lenovo",
    priceIdr: 14_999_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=Lenovo+LOQ",
    shortDesc: "Gaming entry: Intel Core i5-13450HX + RTX 4060, IPS 144Hz",
    specs: {
      cpu: "Intel Core i5-13450HX (10 core, 4.6 GHz boost)",
      gpu: "NVIDIA GeForce RTX 4060 8GB GDDR6",
      ram: "16 GB DDR5 4800MHz",
      storage: "512 GB NVMe SSD",
      display: {
        size: "15.6 inci",
        resolution: "1920 x 1080",
        type: "IPS",
        refreshRate: "144Hz",
      },
      battery: { capacity: "60 Wh", charging: "135W" },
      os: "Windows 11 Home",
      ports: "2x USB-A 3.1, 1x USB-C, 1x HDMI 2.1, RJ45, 3.5mm",
      keyboard: "Backlit",
      connectivity: "Wi-Fi 6, Bluetooth 5.1",
      weight: "2.4 kg",
    },
    sourceUrl: "https://www.lenovo.com/id/id/laptops/loq/",
  },
  {
    name: "Acer Nitro V 15",
    slug: "acer-nitro-v-15",
    category: "LAPTOP" as const,
    brandSlug: "acer",
    priceIdr: 11_999_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=Nitro+V+15",
    shortDesc: "Gaming mid-range: Ryzen 5 7535HS + RTX 4050, IPS 144Hz",
    specs: {
      cpu: "AMD Ryzen 5 7535HS (6 core, 4.55 GHz boost)",
      gpu: "NVIDIA GeForce RTX 4050 6GB GDDR6",
      ram: "16 GB DDR5",
      storage: "512 GB NVMe SSD",
      display: {
        size: "15.6 inci",
        resolution: "1920 x 1080",
        type: "IPS",
        refreshRate: "144Hz",
      },
      battery: { capacity: "57.5 Wh", charging: "135W" },
      os: "Windows 11 Home",
      ports: "1x USB-A 3.2, 2x USB-A 3.1, 1x USB-C, 1x HDMI 2.1, RJ45, SD card",
      keyboard: "4-zone RGB backlit",
      connectivity: "Wi-Fi 6, Bluetooth 5.1",
      weight: "2.3 kg",
    },
    sourceUrl: "https://www.acer.com/id-id/laptops/nitro/nitro-v",
  },
  {
    name: "HP Laptop 14s-dq5",
    slug: "hp-laptop-14s-dq5",
    category: "LAPTOP" as const,
    brandSlug: "hp-inc",
    priceIdr: 6_499_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=HP+Laptop+14s",
    shortDesc: "Budget laptop tipis Intel i3-1215U, 14\" FHD, ideal pelajar & kerja",
    specs: {
      cpu: "Intel Core i3-1215U (6 core, 4.4 GHz boost)",
      gpu: "Intel UHD Graphics",
      ram: "8 GB DDR4",
      storage: "256 GB NVMe SSD",
      display: {
        size: "14 inci",
        resolution: "1920 x 1080",
        type: "IPS Anti-glare",
        refreshRate: "60Hz",
      },
      battery: { capacity: "41.6 Wh", charging: "45W" },
      os: "Windows 11 Home",
      ports: "2x USB-A 3.1, 1x USB-C, 1x HDMI, 3.5mm",
      keyboard: "Full-size",
      connectivity: "Wi-Fi 5, Bluetooth 5",
      weight: "1.46 kg",
    },
    sourceUrl: "https://www.hp.com/id-id/shop/laptops",
  },
  {
    name: "ASUS Vivobook 14 M1405",
    slug: "asus-vivobook-14-m1405",
    category: "LAPTOP" as const,
    brandSlug: "asus",
    priceIdr: 8_499_000,
    imageUrl: "https://placehold.co/400x500/1a1a2e/white?text=Vivobook+14+M1405",
    shortDesc: "Ryzen 5 7530U, 14\" OLED 90Hz 2.8K, ringan 1.38 kg cocok mobilitas",
    specs: {
      cpu: "AMD Ryzen 5 7530U (6 core, 4.5 GHz boost)",
      gpu: "AMD Radeon Graphics (integrated)",
      ram: "8 GB DDR4",
      storage: "512 GB PCIe SSD",
      display: {
        size: "14 inci",
        resolution: "2880 x 1800",
        type: "OLED",
        refreshRate: "90Hz",
      },
      battery: { capacity: "50 Wh", charging: "65W USB-C" },
      os: "Windows 11 Home",
      ports: "1x USB-A 3.2, 1x USB-A 2.0, 1x USB-C, 1x HDMI, 3.5mm",
      keyboard: "Backlit",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      weight: "1.38 kg",
    },
    sourceUrl: "https://www.asus.com/id/laptops/for-home/vivobook/",
  },
];

async function main() {
  console.log("🌱 Seeding database...");

  // Upsert brands
  for (const brand of brands) {
    await prisma.brand.upsert({
      where: { slug: brand.slug },
      update: {},
      create: brand,
    });
    console.log(`  ✓ Brand: ${brand.name}`);
  }

  // Upsert gadgets
  for (const gadget of gadgets) {
    const { brandSlug, ...data } = gadget;
    const brand = await prisma.brand.findUniqueOrThrow({ where: { slug: brandSlug } });
    await prisma.gadget.upsert({
      where: { slug: data.slug },
      update: {
        ...data,
        brandId: brand.id,
        lastVerifiedDate: new Date("2026-09-08"),
      },
      create: {
        ...data,
        brandId: brand.id,
        lastVerifiedDate: new Date("2026-09-08"),
      },
    });
    console.log(`  ✓ Gadget: ${data.name}`);
  }

  console.log(`\n✅ Seeded ${brands.length} brands & ${gadgets.length} gadgets`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
